/* Microchip Technology Inc. and its subsidiaries.  You may use this software 
 * and any derivatives exclusively with Microchip products. 
 * 
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS".  NO WARRANTIES, WHETHER 
 * EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED 
 * WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A 
 * PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP PRODUCTS, COMBINATION 
 * WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION. 
 *
 * IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
 * INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
 * WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS 
 * BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE 
 * FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS 
 * IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF 
 * ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 * MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE 
 * TERMS. 
 */

/*******************************************************************************
  This source file has NOT been generated by the MHC
 *******************************************************************************/

/* 
 * File:   
 * Author: 
 * Comments:
 * Revision history: 
 */

// *****************************************************************************
// *****************************************************************************
// Section: Included Files 
// *****************************************************************************
// *****************************************************************************
#ifdef __XC32
    #include <xc.h>          /* Defines special function registers, CP0 regs  */
#endif

#include <stdint.h>
#include "OLED.h"

// *****************************************************************************
// *****************************************************************************
// Section: Global Data Definitions
// *****************************************************************************
// *****************************************************************************



// *****************************************************************************
// *****************************************************************************
// Section: User Functions
// *****************************************************************************
// *****************************************************************************

// Comment a function definition and leverage automatic documentation 
/**
  <p><b>Function:</b></p>

  <p><b>Summary:</b></p>

  <p><b>Description:</b></p>

  <p><b>Remarks:</b></p>
 */
// TODO Insert function definitions (right here) to leverage live documentation
/* ------------------------------------------------------------ */
/*** OledPutBuffer
**
** Parameters:
** cb - number of bytes to send/receive
** rgbTx - pointer to the buffer to send
**
** Return Value:
** none
**
** Errors:
** none
**
** Description:
** Send the bytes specified in rgbTx to the slave.
*/
void
OledPutBuffer(int cb, BYTE * rgbTx)
{
    int ib;
    BYTE bTmp;
    /* Write/Read the data
    */
    for (ib = 0; ib < cb; ib++) {
        /* Wait for transmitter to be ready
        */
        while (SPI2STATbits.SPITBE == 0);
        /* Write the next transmit byte.
        */
        SPI2BUF = *rgbTx++;
        /* Wait for receive byte.
        */
        while (SPI2STATbits.SPIRBF == 0);
        bTmp = SPI2BUF;
    }
}
/* ------------------------------------------------------------ */
/*** Spi2PutByte
**
** Parameters:
** bVal - byte value to write
**
** Return Value:
** Returns byte read
**
** Errors:
** none
**
** Description:
** Write/Read a byte on SPI port 2
 * */
BYTE
Spi2PutByte(BYTE bVal)
{
    BYTE bRx;
    /* Wait for transmitter to be ready
    */
    while (SPI2STATbits.SPITBE == 0);
    /* Write the next transmit byte.
    */
    SPI2BUF = bVal;
    /* Wait for receive byte.
    */
    while (SPI2STATbits.SPIRBF == 0);
    /* Put the received byte in the buffer.
    */
    bRx = SPI2BUF;
    return bRx;
}